"""
Exporter — generates TXT, PDF, SRT, DOCX from transcription sessions.
All libraries are free and open-source.
"""
import io
import datetime


# ── TXT ──────────────────────────────────────────────────────────────────────

def export_txt(text: str, session: dict) -> str:
    lines = [
        '=' * 60,
        'SUBTITLE ASSISTANT — TRANSCRIPTION',
        '=' * 60,
        f"Title    : {session.get('title', 'Untitled')}",
        f"Date     : {session.get('date', '')}",
        f"Mode     : {session.get('mode', 'unknown').upper()}",
        f"Language : {session.get('detected_language', 'unknown').upper()}",
        f"Words    : {len(text.split())}",
        '=' * 60,
        '',
        '— TRANSCRIPTION —',
        '',
        text,
    ]

    if session.get('translated_text'):
        lines += [
            '',
            f"— TRANSLATION ({session.get('target_language', '').upper()}) —",
            '',
            session['translated_text'],
        ]

    lines += ['', '=' * 60, 'Generated by AI-Powered Subtitle Assistant', '=' * 60]
    return '\n'.join(lines)


# ── PDF ──────────────────────────────────────────────────────────────────────

def export_pdf(text: str, session: dict) -> bytes:
    try:
        from reportlab.lib.pagesizes import A4
        from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
        from reportlab.lib.units import cm
        from reportlab.lib import colors
        from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, HRFlowable, Table, TableStyle
        from reportlab.lib.enums import TA_LEFT, TA_CENTER

        buf = io.BytesIO()
        doc = SimpleDocTemplate(
            buf,
            pagesize=A4,
            leftMargin=2*cm, rightMargin=2*cm,
            topMargin=2.5*cm, bottomMargin=2*cm
        )

        styles = getSampleStyleSheet()
        DARK = colors.HexColor('#0d1117')
        CYAN = colors.HexColor('#00d4ff')
        PURPLE = colors.HexColor('#b829f5')
        GRAY = colors.HexColor('#8b949e')

        title_style = ParagraphStyle('Title', fontSize=22, textColor=CYAN,
                                     fontName='Helvetica-Bold', alignment=TA_CENTER,
                                     spaceAfter=4)
        sub_style = ParagraphStyle('Sub', fontSize=10, textColor=GRAY,
                                   fontName='Helvetica', alignment=TA_CENTER, spaceAfter=12)
        meta_style = ParagraphStyle('Meta', fontSize=10, textColor=DARK,
                                    fontName='Helvetica', spaceAfter=4)
        body_style = ParagraphStyle('Body', fontSize=11, textColor=DARK,
                                    fontName='Helvetica', leading=18, spaceAfter=6)
        section_style = ParagraphStyle('Section', fontSize=13, textColor=PURPLE,
                                       fontName='Helvetica-Bold', spaceBefore=14, spaceAfter=6)

        story = []
        story.append(Paragraph('🎙 AI Subtitle Assistant', title_style))
        story.append(Paragraph('Transcription Export', sub_style))
        story.append(HRFlowable(width='100%', thickness=1, color=CYAN))
        story.append(Spacer(1, 0.3*cm))

        # Metadata table
        meta_data = [
            ['Title:', session.get('title', 'Untitled')],
            ['Date:', session.get('date', '')],
            ['Mode:', session.get('mode', 'unknown').upper()],
            ['Language:', session.get('detected_language', 'unknown').upper()],
            ['Word Count:', str(len(text.split()))],
        ]
        t = Table(meta_data, colWidths=[3*cm, 12*cm])
        t.setStyle(TableStyle([
            ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
            ('FONTNAME', (1, 0), (1, -1), 'Helvetica'),
            ('FONTSIZE', (0, 0), (-1, -1), 10),
            ('TEXTCOLOR', (0, 0), (0, -1), PURPLE),
            ('TEXTCOLOR', (1, 0), (1, -1), DARK),
            ('TOPPADDING', (0, 0), (-1, -1), 3),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 3),
        ]))
        story.append(t)
        story.append(Spacer(1, 0.4*cm))
        story.append(HRFlowable(width='100%', thickness=0.5, color=colors.HexColor('#e0e0e0')))
        story.append(Spacer(1, 0.3*cm))

        story.append(Paragraph('Transcription', section_style))
        # Split text into paragraphs — escape XML-unsafe chars for ReportLab
        for para in text.split('\n'):
            if para.strip():
                safe = para.strip().replace('&', '&amp;').replace('<', '&lt;').replace('>', '&gt;')
                story.append(Paragraph(safe, body_style))

        if session.get('translated_text'):
            story.append(Spacer(1, 0.5*cm))
            story.append(HRFlowable(width='100%', thickness=0.5, color=colors.HexColor('#e0e0e0')))
            tl = session.get('target_language', '').upper()
            story.append(Paragraph(f'Translation ({tl})', section_style))
            for para in session['translated_text'].split('\n'):
                if para.strip():
                    safe = para.strip().replace('&', '&amp;').replace('<', '&lt;').replace('>', '&gt;')
                    story.append(Paragraph(safe, body_style))

        story.append(Spacer(1, 0.8*cm))
        story.append(HRFlowable(width='100%', thickness=1, color=CYAN))
        story.append(Paragraph('Generated by AI-Powered Subtitle Assistant', sub_style))

        doc.build(story)
        return buf.getvalue()

    except ImportError:
        # Fallback: simple text-based PDF won't be pretty but won't crash
        raise RuntimeError("reportlab is not installed. Run: pip install reportlab")


# ── SRT ──────────────────────────────────────────────────────────────────────

def export_srt(segments: list, fallback_text: str) -> str:
    """Generate SRT subtitle format with timestamps."""
    if not segments:
        # No segments — wrap whole text in one block
        return f"1\n00:00:00,000 --> 00:05:00,000\n{fallback_text}\n"

    lines = []
    for i, seg in enumerate(segments, 1):
        start = _seconds_to_srt(seg.get('start', 0))
        end = _seconds_to_srt(seg.get('end', seg.get('start', 0) + 3))
        text = seg.get('text', '').strip()
        if text:
            lines.append(f"{i}\n{start} --> {end}\n{text}\n")

    return '\n'.join(lines)


def _seconds_to_srt(seconds: float) -> str:
    h = int(seconds // 3600)
    m = int((seconds % 3600) // 60)
    s = int(seconds % 60)
    ms = int((seconds - int(seconds)) * 1000)
    return f"{h:02d}:{m:02d}:{s:02d},{ms:03d}"


# ── DOCX ─────────────────────────────────────────────────────────────────────

def export_docx(text: str, session: dict) -> bytes:
    try:
        from docx import Document
        from docx.shared import Pt, RGBColor, Inches
        from docx.enum.text import WD_ALIGN_PARAGRAPH

        doc = Document()

        # Title
        title = doc.add_heading('AI Subtitle Assistant — Transcription', 0)
        title.alignment = WD_ALIGN_PARAGRAPH.CENTER
        title.runs[0].font.color.rgb = RGBColor(0, 212, 255)

        doc.add_paragraph()

        # Metadata
        meta = [
            ('Title', session.get('title', 'Untitled')),
            ('Date', session.get('date', '')),
            ('Mode', session.get('mode', 'unknown').upper()),
            ('Language', session.get('detected_language', 'unknown').upper()),
            ('Word Count', str(len(text.split()))),
        ]
        table = doc.add_table(rows=len(meta), cols=2)
        table.style = 'Light Grid Accent 1'
        for i, (k, v) in enumerate(meta):
            row = table.rows[i]
            row.cells[0].text = k
            row.cells[1].text = v
            row.cells[0].paragraphs[0].runs[0].bold = True

        doc.add_paragraph()

        # Transcription
        h = doc.add_heading('Transcription', level=1)
        h.runs[0].font.color.rgb = RGBColor(184, 41, 245)

        for para in text.split('\n'):
            if para.strip():
                p = doc.add_paragraph(para.strip())
                p.runs[0].font.size = Pt(11)

        if session.get('translated_text'):
            doc.add_paragraph()
            tl = session.get('target_language', '').upper()
            h2 = doc.add_heading(f'Translation ({tl})', level=1)
            h2.runs[0].font.color.rgb = RGBColor(184, 41, 245)
            for para in session['translated_text'].split('\n'):
                if para.strip():
                    p = doc.add_paragraph(para.strip())
                    p.runs[0].font.size = Pt(11)

        doc.add_paragraph()
        footer_p = doc.add_paragraph('Generated by AI-Powered Subtitle Assistant')
        footer_p.alignment = WD_ALIGN_PARAGRAPH.CENTER
        footer_p.runs[0].font.color.rgb = RGBColor(139, 148, 158)
        footer_p.runs[0].font.size = Pt(9)

        buf = io.BytesIO()
        doc.save(buf)
        return buf.getvalue()

    except ImportError:
        raise RuntimeError("python-docx is not installed. Run: pip install python-docx")
